-- Insert sample works entries
INSERT INTO public.works (title, slug, industry, thumbnail, tags, tech_stack, metrics, featured, challenge_md, solution_md, result_md, live_url) VALUES
(
  'Offline-First Logistics App',
  'logistics-offline-app',
  'Android App Development',
  'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80',
  ARRAY['Android', 'Kotlin', 'Room', 'Offline-First'],
  ARRAY['Kotlin', 'Jetpack Compose', 'Room', 'WorkManager', 'Supabase'],
  '[{"label": "Sync Latency", "value": "-95%"}, {"label": "Battery Optimization", "value": "+30%"}]'::jsonb,
  true,
  'Logistics company drivers struggled to update shipment statuses in rural regions with unstable mobile networks, leading to delayed tracking updates.',
  'Built a native Android app with an offline-first SQLite database using Room. Enqueued background status updates via WorkManager when connection is restored.',
  'Eliminated status sync drop-offs, reduced local database sync latency by 95%, and saved driver device battery consumption by 30%.',
  'https://example.com/logistics-demo'
),
(
  'SaaS Analytics Dashboard',
  'saas-analytics-dashboard',
  'SaaS Platform Engineering',
  'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80',
  ARRAY['SaaS', 'Dashboard', 'Analytics', 'B2B'],
  ARRAY['React', 'Next.js', 'TypeScript', 'Supabase', 'D3.js'],
  '[{"label": "User Retention", "value": "+56%"}, {"label": "Time on Platform", "value": "+3.2x"}]'::jsonb,
  true,
  'B2B SaaS company had fragmented data across multiple tools, making it hard for users to get insights.',
  'Built a unified analytics dashboard with real-time data visualization, custom reports, and automated alerts.',
  'User retention improved by 56% and average time on platform increased 3.2x.',
  'https://dashboard-demo.example.com'
),
(
  'AI-Powered Customer Support Bot',
  'ai-customer-support-bot',
  'AI & LLM Integrations',
  'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&q=80',
  ARRAY['AI', 'Chatbot', 'Automation', 'NLP'],
  ARRAY['OpenAI', 'Python', 'FastAPI', 'React'],
  '[{"label": "Response Time", "value": "-85%"}, {"label": "Customer Satisfaction", "value": "+42%"}]'::jsonb,
  true,
  'Client needed to handle 10,000+ daily support tickets with a small team, leading to long wait times and frustrated customers.',
  'Built an intelligent chatbot using GPT-4 that handles common queries, escalates complex issues, and learns from interactions.',
  'Reduced average response time from 4 hours to 35 minutes while improving CSAT scores by 42%.',
  'https://example.com/demo'
),
(
  'Figma Design System for SaaS',
  'figma-design-system-saas',
  'UI/UX Design Systems',
  'https://images.unsplash.com/photo-1618788372246-79faff0c3742?w=800&q=80',
  ARRAY['Design System', 'UI/UX', 'Figma', 'Tokens'],
  ARRAY['Figma', 'React', 'Tailwind CSS', 'Storybook'],
  '[{"label": "Design Consistency", "value": "100%"}, {"label": "Development Handover", "value": "2x Faster"}]'::jsonb,
  false,
  'B2B tech startup had disjointed web and mobile interfaces, causing brand inconsistency and slowing down developers.',
  'Created a comprehensive Figma design system with structured component tokens, responsive layouts, and auto-layout styling rules.',
  'Achieved 100% UI consistency across platforms and accelerated developer handoff time by 50%.',
  'https://figma.com/file/example'
),
(
  'Native Android E-Commerce App',
  'native-android-ecommerce',
  'Android App Development',
  'https://images.unsplash.com/photo-1601972599720-36938d4ecd31?w=800&q=80',
  ARRAY['E-Commerce', 'Android', 'Kotlin', 'Material Design'],
  ARRAY['Kotlin', 'Jetpack Compose', 'Google Pay', 'Firebase'],
  '[{"label": "Mobile Conversions", "value": "+48%"}, {"label": "App Store Rating", "value": "4.8"}]'::jsonb,
  true,
  'Retail brand experienced extremely high checkout abandonment rates on mobile browsers.',
  'Built a native Android e-commerce application using Jetpack Compose with Google Pay integration for one-tap checkout.',
  'Increased mobile conversions by 48% and achieved a 4.8-star rating on the Google Play Store.',
  'https://example.com/ecommerce-android-demo'
),
(
  'AI-Integrated SaaS Document Search',
  'ai-saas-document-search',
  'AI & LLM Integrations',
  'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&q=80',
  ARRAY['AI', 'SaaS', 'RAG', 'Vector Search'],
  ARRAY['Next.js', 'OpenAI API', 'Pgvector', 'Supabase'],
  '[{"label": "Search Precision", "value": "+92%"}, {"label": "Query Latency", "value": "<200ms"}]'::jsonb,
  false,
  'Legal firm took hours querying unstructured documents and case files for exact clauses.',
  'Engineered a semantic RAG (Retrieval-Augmented Generation) document search tool using OpenAI embeddings and pgvector storage.',
  'Increased search precision by 92% and reduced query lookup latency to under 200ms.',
  NULL
);
